config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Chatrooms controller
  resources :chat_rooms, except: [:update]

  # Action cable
  mount ActionCable.server => '/cable'

  # Default route
  root 'chat_rooms#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user

  # Associations
  has_many :messages, dependent: :destroy

  # Validations
  validates :title, presence: true

end

app/models/message.rb
class Message < ApplicationRecord
  # Enum
  # Text is used when bob sends a message to alice
  # Info is used to notice when users enter and leave the room
  enum mtype: { text: 0, info: 1 }

  # Callbacks
  after_create_commit { MessageBroadcastJob.perform_later(self) }

  # Associations
  belongs_to :user
  belongs_to :chat_room

  # Validations
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
  validates :mtype, presence: true

  # Convert created at to time
  def get_time
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  # Associations
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  # Shows the nickname stripping the email
  def nick_name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Restrict all pages only to authenticated users
  before_action :authenticate_user!
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def show
    # Includes method is used to eager loading
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new

    redirect_to chat_rooms_path if @chat_room.nil?
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    # Automatically fill the user id
    @chat_room = current_user.chat_rooms.build(chat_room_params)

    if @chat_room.save
      flash[:success] = t('messages.added', item: 'Chat Room')
      redirect_to chat_rooms_path
    else
      render :new
    end
  end

  def destroy
    @chat_room = ChatRoom.find(params[:id])

    if current_user = @chat_room.user
      if @chat_room.destroy
        redirect_to chat_rooms_path, notice: t('messages.destroyed')
      else
        redirect_to chat_rooms_path, error: t('messages.ndestroyed')
      end
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.nick_name
    puts Digest::MD5.hexdigest(user.email)
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end

  def flash_class(level)
    case level
        when 'notice' then 'alert alert-info'
        when 'success' then 'alert alert-success'
        when 'error' then 'alert alert-error'
        when 'alert' then 'alert alert-error'
    end
  end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/chat_rooms/index.html.erb
<h1><%= t('app.title') %></h1>

<% if @chat_rooms.nil? %>

  <div class="jumbotron">
    <h1><%= t('app.welcome') %></h1>
    <p>
      <%= t('messages.empty_chat_rooms') %>
    </p>
    <p class="lead">
      <%= link_to t('buttons.new', item: 'chat room'),
                      new_chat_room_path, class: 'btn btn-primary btn-lg',
                      role: 'button' %>
    </p>
  </div>

<% else %>

  <p class="lead">
    <%= link_to t('buttons.new', item: 'chat room'),
                      new_chat_room_path, class: 'btn btn-primary' %>
  </p>

  <div class="table-responsive">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th class="col-md-7"> <%= ChatRoom.human_attribute_name('title') %> </td>
          <th class="col-md-3"> <%= ChatRoom.human_attribute_name('created_at') %> </td>
          <th colspan="2">
            <%= t('buttons.action') %>
          </td>
        </tr>
      </thead>
      <tbody>
        <% @chat_rooms.each  do |c| %>
          <tr>
            <td> <%= c.title %> </td>
            <td> <%= time_ago_in_words(c.created_at) %> </td>
            <td align="center"> <%= link_to t('buttons.enterwo'), chat_room_path(c.id), class: 'btn btn-primary' %></td>

            <% if current_user != c.user %>
              <td  align="center">
                <%= link_to t('buttons.destroy'), chat_room_path(c.id), method: :delete,
               data: { confirm: t('messages.delete') }, class: 'btn btn-danger disabled' %>
             </td>
            <% else %>
              <td align="center">
                  <%= link_to t('buttons.destroy'), chat_room_path(c.id), method: :delete,
                 data: { confirm: t('messages.delete') }, class: 'btn btn-danger' %>
             </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/chat_rooms/new.html.erb
<h1><%= t('messages.add', item: 'chat room') %></h1>

<%= form_for @chat_room do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit t('buttons.add'), class: 'btn btn-primary' %>

<% end %>

app/views/chat_rooms/show.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading"><%= @chat_room.title %></div>
      <div class="panel-body">
        <div class="message-wrap">
          <!-- each message -->
          <div class="msg-wrap">
            <div id="messages" data-chat-room-id="<%= @chat_room.id %>">
              <%= render @chat_room.messages %>
            </div>
          </div>

          <%= form_for @message, url: '' do |f| %>
            <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
            <div class="send-wrap form-group">
              <%= f.label :body %>
              <%= f.text_area :body, class: 'form-control send-message', rows: '3',
                                     placeholder: t('messages.typetext') %>
              <small class="text-muted"><%= t('messages.max_char') %></small>
            </div>

            <div class="btn-panel">
              <%= f.submit t('buttons.post'), class: 'col-lg-2 text-right btn send-message-btn pull-right',
              role: 'button' %>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <p class="navbar-text"><%= t('app.header') %></p>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav pull-right">
                <% if current_user %>
                    <li><%= link_to t('app.chatroom'), chat_rooms_path %></li>
                    <li><%= link_to t('app.signout'), destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to t('app.signin'), new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>

    <div id="wrapper" class="toggled">
      <div id="page-content-wrapper">
        <div class="container-fluid">
          <%= render partial: 'layouts/notifications' %>
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/messages/_message.html.erb
<div class="media msg">
    <a class="pull-left" href="">
        <%= gravatar_for message.user %>
    </a>
    <div class="media-body">
        <small class="pull-right time"><i class="fa fa-clock-o"></i> <%= time_ago_in_words(message.created_at) %> </small>

        <h5 class="media-heading"><%= message.user.nick_name %></h5>
        <small class="col-lg-10">
          <%= message.body %>
        </small>
    </div>
</div>